apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flask
        image: fefone/backend:v1  # Sostituisci con la tua immagine
        ports:
        - containerPort: 5000  # Porta dell'API Flask
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_SERVICE_SERVICE_HOST
          value: "postgres-service"
        - name: POSTGRES_SERVICE_SERVICE_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000      # Porta del Service
      targetPort: 5000  # Porta del container
