apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
  - host: k8s-basic.local  # Dominio fittizio (devi aggiungerlo a /etc/hosts)
    http:
      paths:
      - path: /           # Tutte le richieste a "/" vanno al frontend
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api        # Tutte le richieste a "/api" vanno al backend
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000