version: '3.8'  # Versione aggiornata

services:
  mongodb:
    image: mongo:latest  # Usa l'ultima versione dell'immagine di MongoDB
    container_name: mongodb
    ports:
      - "27017:27017"  # Mappa la porta 27017 del container alla porta 27017 dell'host
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersecret

  mongo-express:
    image: mongo-express:latest  # Usa l'ultima versione dell'immagine di mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"  # Mappa la porta 8081 del container alla porta 8081 dell'host
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecret
      ME_CONFIG_MONGODB_SERVER: mongodb