version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "3001:3001"  # Correzione della porta
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb  # Connessione al database
      - REDIS_URL=redis://redis:6379  # Connessione a Redis (se utilizzato)
    depends_on:
      - db
      - redis  # Assicurati che Redis sia disponibile
    networks:
      - app_network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Assicurati che il file init.sql sia mappato
    networks:
      - app_network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
