version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd "My Node App"
      - npm install
  build:
    commands:
      - cd "My Node App"
      - npm run build
artifacts:
  files:
    - 'My Node App/**/*'
  discard-paths: yes