version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Usa Node.js 16 (o una versione supportata)
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes