version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd cicd_pipeline_codepipeline_codebuild/my_node_app
      - npm install
  build:
    commands:
      - cd cicd_pipeline_codepipeline_codebuild/my_node_app
      - npm run build
artifacts:
  files:
    - 'cicd_pipeline_codepipeline_codebuild/my_node_app/**/*'
  discard-paths: yes